# Generated by Django 5.1 on 2024-09-18 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Catalog', '0004_product_views_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='slug'),
        ),
    ]
