# Generated by Django 5.1 on 2024-09-21 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Catalog', '0006_version'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='version',
            options={'ordering': ['version_name'], 'verbose_name': 'Product_category', 'verbose_name_plural': 'Products_category'},
        ),
    ]
