# Generated by Django 5.1 on 2024-09-21 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Catalog', '0007_alter_version_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='version',
            options={'ordering': ['version_name'], 'verbose_name': 'Version', 'verbose_name_plural': 'Versions'},
        ),
    ]
