# Generated by Django 4.2.2 on 2024-09-28 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Catalog', '0009_alter_version_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name'], 'permissions': [('can_edit_is_published', 'Can edit is published'), ('can_edit_description', 'Can edit description'), ('can_edit_category', 'Can edit category')], 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
    ]
